spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.11.238:3306/gulimall_pms?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.238:8848
    alicloud:
      access-key: LTAI4G1BHzmyRDVHurCQp6TM
      secret-key: IxvMHrLqbkNN2qhZJypFeV9RHNVzkt
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.11.238
    port: 6379
#
#
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8810
logging:
  level:
    com.atguigu.gulimall: info

